name: CI

on:
  workflow_run:
    workflows: [ "Validate tags" ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: update tags
        run: |
          jq -s 'flatten' tokens/*.json > merged.json;

          curl -X 'POST' \
              ${{ secrets.URL_1 }} \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F 'file=@merged.json;type=application/json'
              
          curl -X 'POST' \
              ${{ secrets.URL_2 }} \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F 'file=@merged.json;type=application/json'

          rm merged.json;
          
          jq -s 'flatten' accounts/*.json > merged.json;

          curl -X 'POST' \
              ${{ secrets.URL_3 }} \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F 'file=@merged.json;type=application/json'
              
          curl -X 'POST' \
              ${{ secrets.URL_4 }} \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F 'file=@merged.json;type=application/json'

          rm merged.json;

          # Atualiza a tag 'elethcoin' no arquivo JSON
          jq '.tags.elethcoin = {
            "chainId": "56",
            "address":"0x61888e283070faec5edf697f97525942ce3a0e3e",
            "symbol": "ELC",
            "name": "TOKEN_elethcoin",
            "tags": ["TOKEN_elethcoin"]
          }' merged.json > updated.json

          # Envia o arquivo updated.json para as URLs desejadas
          curl -X 'POST' \
              ${{ secrets.URL_1 }} \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F 'file=@updated.json;type=application/json'

          curl -X 'POST' \
              ${{ secrets.URL_2 }} \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F 'file=@updated.json;type=application/json'

          curl -X 'POST' \
              ${{ secrets.URL_3 }} \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F 'file=@updated.json;type=application/json'

          curl -X 'POST' \
              ${{ secrets.URL_4 }} \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F 'file=@updated.json;type=application/json'

          rm updated.json

