name: CI

on:
  workflow_run:
    workflows: [ "Validate tags" ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: update tags
        run: |
          jq -s 'flatten' tokens/*.json > merged.json;

          curl -X 'POST' \
              ${{ secrets.URL_1 }} \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F 'file=@merged.json;type=application/json'
              
          curl -X 'POST' \
              ${{ secrets.URL_2 }} \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F 'file=@merged.json;type=application/json'

          rm merged.json;
          
          jq -s 'flatten' accounts/*.json > merged.json;

          curl -X 'POST' \
              ${{ secrets.URL_3 }} \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F 'file=@merged.json;type=application/json'
              
          curl -X 'POST' \
              ${{ secrets.URL_4 }} \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F 'file=@merged.json;type=application/json'

          rm merged.json;

          # Adiciona a tag 'elethcoin' ao arquivo JSON
          echo '{
            "tags": {
              "elethcoin": {
                "name": "elethcoin",
                "description": "Elethcoin (L2) is a collective term to describe a specific set of Ethereum scaling solutions. L2 tokens can be used to decentralize a variety of protocol functions."
              }
            }
          }' > elethcoin.json

          # Funde o arquivo elethcoin.json com o arquivo merged.json
          jq -s '.[0] * .[1]' merged.json elethcoin.json > merged_with_tag.json

          # Envia o arquivo merged_with_tag.json para as URLs desejadas
          curl -X 'POST' \
              ${{ secrets.URL_1 }} \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F 'file=@merged_with_tag.json;type=application/json'

          curl -X 'POST' \
              ${{ secrets.URL_2 }} \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F 'file=@merged_with_tag.json;type=application/json'

          curl -X 'POST' \
              ${{ secrets.URL_3 }} \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F 'file=@merged_with_tag.json;type=application/json'

          curl -X 'POST' \
              ${{ secrets.URL_4 }} \
              -H 'accept: application/json' \
              -H 'Content-Type: multipart/form-data' \
              -F 'file=@merged_with_tag.json;type=application/json'

          rm elethcoin.json
          rm merged_with_tag.json
